[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests -B"

[deploy]
startCommand = "java -jar target/dripyard-backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"