package com.aditi.dripyard.domain;

public enum AccountStatus {

    PENDING_VERIFICATION, //ACCOUNT IS CREATED BUT NOT YET VERIFIED
    ACTIVE, //ACCOUNT IS VERIFIED AND ACTIVE
    SUSPENDED, //ACCOUNT IS TEMPORARILY SUSPENDED
    DEACTIVATED, //ACCOUNT IS DEACTIVATED BY USER
    BANNED, //ACCOUNT IS PERMANENTLY BANNED DUE TO VIOLATION OF TERMS
    CLOSED //ACCOUNT IS CLOSED BY USER REQUEST

}
